name: Deploy to Neocities
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
steps:
  uses: jonchang/deploy-neocities@e557d8b4aa935cd3e1a437c038bb043c9b4064f6
  with:
    # Required, to access Neocities API.
    # https://neocities.org/settings
    # Set in Settings -> Secrets
    key: ${{ secrets.NEOCITIES_API_KEY }}
    # Required, local directory to deploy to Neocities
    dir: _site
    # Optional, if true, delete remote files not present locally
    clean: false
